<img src="images\Logo_UCLL_ENG_RGB.png" style="background-color:white;" />

# Data Analytics & Machine learning

Lecturers: Aimée Lynn Backiel, Lies Bollens, Fien Van de Woestijne

Academic year 2026-2027


## Lab 2: Introduction to the case and Pandas refresher

### Lecture outline

1. Introduction to the case
2. Data exploration using Pandas
   1. Univariate analysis
   2. Bivariate analysis

### The case

Ada Lovelace Travelogue, or as everyone calls her, Ada just started working part time at her parents travel agency. She has a keen understanding and interest of everything related to applied computer science ranging from server & system management to full stack software development. Through database foundations she already understands how to query data and programming 1 and 2 covered the essentials about the Python programming language. Recently she has just decided to start learning about data analytics & machine learning as well.

She uses her skills to connect to the travel agency's database where she finds many, normalized, tables. Ada recalls what she learnt in database foundations and performs all the correct joins. Afterwards she saves the data in the `data/` folder.


She finds the following dataset:

| Column Name          | Description                                                                                       |
| -------------------- | ------------------------------------------------------------------------------------------------- |
| SalesID              | Unique identifier for each sale.                                                                  |
| Age                  | Age of the traveler.                                                                              |
| Country              | Country of origin of the traveler.                                                                |
| Membership_Status    | Membership level of the traveler in the booking system; could be 'standard', 'silver', or 'gold'. |
| Previous_Purchases   | Number of previous bookings made by the traveler.                                                 |
| Destination          | Travel destination chosen by the traveler.                                                        |
| Stay_length          | Duration of stay at the destination.                                                              |
| Guests               | Number of guests traveling (including the primary traveler).                                             |
| Travel_month         | Month in which the travel is scheduled.                                                           |
| Months_before_travel | Number of months prior to travel that the booking was made.                                       |
| Earlybird_discount   | Boolean flag indicating whether the traveler received an early bird discount.                     |
| Package_Type         | Type of travel package chosen by the traveler.                                                    |
| Cost                 | Calculated cost of the travel package.                                                            |
| Margin | The cost (for the traveler) - what the travel agency pays. |
 | Additional_Services_Cost| The amount of additional services (towels, car rentals, room service, ...) that was bought during the trip. |

### Helping Ada explore the dataset

The main goal for the remainder of this lab is to explore the data. We will specifically take four columns:

* Cost
* age
* stay length
* Destination

Our goal is to find interesting relationships between them.

As was covered in the book and lecture there are to main data types in analytics: categorical and continuous data. This is a crucial first step in your analysis because it determines what methods make sense on your data.

**The goal is primarily to find out what influences the cost of the stay.**

### Introduction to Pandas

<center><img src="images\pandas_logo.png"  style="background-color:white;"></center>

Pandas stands for panel data, a type of dataset used in economics. Although this was the reason Pandas was invented, it is widely used in across analytics and one of Python's many "killer apps". Essentially, it's a package that makes Python unique compared to some of its competitors.

#### Installing Pandas


Before we start it is a good idea to check if you have pandas installed yet. You can do that with the following command in a notebook cell `pip list`. Notice the exclamation mark (!), it allows you to run things in a code cell as it were a terminal. You can also open the terminal itself and write `pip list`.

In [34]:
%pip list

Package                 Version
----------------------- -----------
asttokens               3.0.2
colorama                0.4.6
comm                    0.2.3
debugpy                 1.8.22
executing               2.2.1
ipykernel               7.4.0
ipython                 9.17.1
ipython_pygments_lexers 1.1.1
jedi                    0.20.0
jupyter_client          8.10.0
jupyter_core            5.9.1
matplotlib-inline       0.2.2
nest-asyncio2           1.7.3
numpy                   2.5.3
packaging               26.3
pandas                  3.0.6
parso                   0.8.7
pip                     25.2
platformdirs            4.12.2
prompt_toolkit          3.0.53
psutil                  7.2.2
pure_eval               0.2.4
Pygments                2.21.0
python-dateutil         2.9.0.post0
pyzmq                   27.2.0
six                     1.17.0
stack-data              0.6.3
tornado                 6.5.10
traitlets               5.16.1
typing_extensions       4.16.0
tzdata                  2026.4
wcwidth                 0.9.1
Note: you may need to restart the kernel to use updated packages.


`pip list` shows you the full set of packages you have installed. If you are making this lab from Google colab Pandas will already be installed. You can double check this with `%pip list | grep pandas`. `|` is the pipe operator which gives the result of the preceding statement to `grep` which searches the text for Pandas. You can run this on unix-based operating systems as well. If you are on Windows you can run the command: `%pip list | findstr pandas`.

In [35]:
%pip list | findstr pandas

pandas                  3.0.6
Note: you may need to restart the kernel to use updated packages.


**❗ If you have a long list of packages and you are not working from google Colab that is likely an indication you're not working from a virtual environment. Follow the instructions that were listed in the beginning of the class, ask us or send us an e-mail.**

If you're working locally and have followed the instructions Pandas will not be installed yet. You can do so by running `pip install pandas` in the terminal or in a code cell (including the % mark).

In [36]:
# Uncomment to install Pandas

%pip install pandas

Requirement already satisfied: pandas in c:\school\jaar_2\data_analytics_and_machine_learning\students2627\name_of_venv\lib\site-packages (3.0.6)
Requirement already satisfied: numpy>=1.26.0 in c:\school\jaar_2\data_analytics_and_machine_learning\students2627\name_of_venv\lib\site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\school\jaar_2\data_analytics_and_machine_learning\students2627\name_of_venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\school\jaar_2\data_analytics_and_machine_learning\students2627\name_of_venv\lib\site-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in c:\school\jaar_2\data_analytics_and_machine_learning\students2627\name_of_venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

#### Reading and exploring data

It's important to know that Pandas is a massive library with a lot of features. For the scope of this course you won't need a lot of it. We recommend you to look at the <a href=./Pandas_Cheat_Sheet.pdf>the cheat sheet</a> to discover what functionality Pandas has. We also recommend you to read the documentation of some of the functions we are using.

Pandas is typically imported as pd by convention. The package makes it incredibly easy to read and write data from different file formats. On top of that it comes with many operations that make working with data easy.

In [37]:
import pandas as pd # by convention

###### 💻📊💡<a href="https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html"> `pd.read_csv` is used to read data from a filepath.</a>

In [38]:
travel_dataset = pd.read_csv("data/lab_1_dataset.csv")

##### ❓ To be sure: did we use a relative or an absolute path?

One of the first things you typically do with a dataset is print out the first few rows.

##### 💻📊💡 <a href=https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.head.html>dataframe.head() prints out the first few lines of the dataframe.</a>

In [39]:
travel_dataset.head()

,sales_id,age,country,membership_status,previous_purchases,destination,stay_length,guests,travel_month,months_before_travel,earlybird_discount,package_Type,cost,rating,margin,additional_services_cost
0,1,47,UK,silver,1,Sydney,3,2,7,1,False,Adventure,288.280435,6,-198.072321,-9.965011
1,2,37,Italy,silver,5,Tokyo,3,2,8,4,False,Adventure,509.870696,7,300.301033,135.941303
2,3,49,USA,standard,2,Sydney,2,4,7,1,False,Cultural,669.761407,6,200.329636,73.148833
3,4,62,Spain,silver,2,Cape Town,6,2,1,3,True,Adventure,1168.585026,7,694.715786,369.316504
4,5,36,Germany,silver,3,Paris,8,3,2,7,False,Adventure,1473.991926,5,1158.133888,330.251646

Accessing the columns is equally trivial.

In [40]:
travel_dataset.columns

Index(['sales_id', 'age', 'country', 'membership_status', 'previous_purchases',
       'destination', 'stay_length', 'guests', 'travel_month',
       'months_before_travel', 'earlybird_discount', 'package_Type', 'cost',
       'rating', 'margin', 'additional_services_cost'],
      dtype='str')

Before we proceed we will take a subset of our dataset cost, age, stay length and destination. Doing so is similar to working with dictionaries.

In [41]:
travel_dataset["country"]

0              UK
1           Italy
2             USA
3           Spain
4         Germany
          ...
9995      Germany
9996    Australia
9997          USA
9998          USA
9999       Canada
Name: country, Length: 10000, dtype: str

In [42]:
travel_dataset["age"]

0       47
1       37
2       49
3       62
4       36
        ..
9995    59
9996    18
9997    29
9998    47
9999    49
Name: age, Length: 10000, dtype: int64

In [43]:
travel_dataset["stay_length"]

0        3
1        3
2        2
3        6
4        8
        ..
9995    10
9996     5
9997     4
9998    15
9999    14
Name: stay_length, Length: 10000, dtype: int64

In [44]:
travel_dataset[["country", "stay_length", "age", "cost"]]

        country  stay_length  age         cost
0            UK            3   47   288.280435
1         Italy            3   37   509.870696
2           USA            2   49   669.761407
3         Spain            6   62  1168.585026
4       Germany            8   36  1473.991926
...         ...          ...  ...          ...
9995    Germany           10   59  2044.329174
9996  Australia            5   18  1291.368165
9997        USA            4   29   946.581809
9998        USA           15   47  3426.801540
9999     Canada           14   49  2925.739153

[10000 rows x 4 columns]

To get multiple columns at once we need to pass in a list of columns

In [45]:
columns = ["country", "stay_length", "age", "cost"]
travel_dataset_subset = travel_dataset[columns]
travel_dataset_subset

        country  stay_length  age         cost
0            UK            3   47   288.280435
1         Italy            3   37   509.870696
2           USA            2   49   669.761407
3         Spain            6   62  1168.585026
4       Germany            8   36  1473.991926
...         ...          ...  ...          ...
9995    Germany           10   59  2044.329174
9996  Australia            5   18  1291.368165
9997        USA            4   29   946.581809
9998        USA           15   47  3426.801540
9999     Canada           14   49  2925.739153

[10000 rows x 4 columns]

#### Intermezzo: Series and Dataframes are mutable

The first important thing to notice about Pandas dataframe is that they are a combination of Pandas Series (columns).

<center><img src="images\df_vs_series.png"  style="background-color:white;"></center>

**❗ Pandas Series and Dataframes are mutable. This can be a big source of frustration and unexpected behavior. This even differs across pandas versions, so we are going to focus on the newest pandas version.**

In [46]:
# The easiest way to make a dataframe is start from a list of dictionaries

students = [{"name": "Omar", "age": 21}, {"name": "Alisha", "age":19}, {"name": "Joost", "age":18}]
students_df = pd.DataFrame(students)
students_df

     name  age
0    Omar   21
1  Alisha   19
2   Joost   18

In [47]:
type(students_df)

pandas.DataFrame

In [48]:
students_df["name"]

0      Omar
1    Alisha
2     Joost
Name: name, dtype: str

In [49]:
type(students_df["name"])

pandas.Series

In [50]:
student_names = students_df["name"]
student_names

0      Omar
1    Alisha
2     Joost
Name: name, dtype: str

In [51]:
# In the newest pandas version, this modifies the series but doesn't modify the dataframe.
student_names[1] = "Katrien"
student_names

0       Omar
1    Katrien
2      Joost
Name: name, dtype: str

In [52]:
#We can see our dataframe has remained unchanged.
students_df

     name  age
0    Omar   21
1  Alisha   19
2   Joost   18

Previous pandas versions would give the following warning: *"A value is trying to be set on a copy of a slice from a DataFrame"* and would actually update the value in the dataframe. As this is confusing for beginners, it's nice that the newest pandas version removed this. If you are still using an older version, be sure to update.

#### Data exploration: univariate

After that short detour we now know that changing our subset `travel_dataset_subset` means we also change our original dataset. We will continue the exploration of our country, stay_length, age and cost variables.

1. We will start with a univariate analysis, which means we will explore one (uni) variable (variate) at a time. 
2. Later on we will move to two (bi) variables (variate) analyses 
3. We round it up with methods that are able to do multivariate analysis.

Recall that 

1. **Categorical variables** represent categories or labels (e.g., colors, genders). 
2. **Numeric variables** represent quantities and can be ordered or measured (e.g., age, height). 
3. There is a special case called **Ordinal variables**, these are categories where there is a meaningful order (e.g., clothes sizes: small, medium and large).

##### ❓ Which variables are categorical and which are numeric?

##### ❓ Do you recall how we can "summarize" or describe numeric variables?

##### ❓ Carry this analysis out on the numeric variable(s).

💻📊💡 TIP: the names of the functions are intuitive. For instance `dataframe[column].min()` gets the minimum of that column. It is equivalent to `select min(column) from dataframe` in SQL. Knowing SQL makes it easy to translate back and forth.

💻📊💡 TIP: become good friends with the <a href=./Pandas_Cheat_Sheet.pdf>the cheat sheet</a> and the documentation

###### Age

In [53]:
students_df["age"].describe()

count     3.000000
mean     19.333333
std       1.527525
min      18.000000
25%      18.500000
50%      19.000000
75%      20.000000
max      21.000000
Name: age, dtype: float64

###### Cost

In [55]:
travel_dataset["cost"].describe()

count    10000.000000
mean      2108.389043
std       1589.021383
min       -652.499948
25%        951.041186
50%       1746.167130
75%       2899.161254
max      14763.867487
Name: cost, dtype: float64

###### stay length

In [56]:
travel_dataset.stay_length.describe()

count    10000.000000
mean         9.491400
std          7.053517
min          0.000000
25%          4.000000
50%          8.000000
75%         13.000000
max         67.000000
Name: stay_length, dtype: float64

##### ❓ Doing this one by one gets quite tedious. Is there any other way listed on the cheat sheet to do this for all variables at once?

##### ❓ Carry this analysis out on the categorical variable(s).

💻📊💡 TIP: `dataframe[column].value_counts()` is a very powerful method. It is equivalent to `select column, count(column) from dataframe group by column`. If you forget `value_counts()` exists you can get there using your SQL knowledge. `dataframe.groupby("column").count()` also gets you very close.

In [57]:
travel_dataset.country.value_counts()

country
UK           1320
Italy        1274
USA          1267
France       1266
Spain        1265
Australia    1222
Canada       1214
Germany      1172
Name: count, dtype: int64

#### Data exploration: bivariate

We will always also look at the combinations of variables and see if those have interesting insights.

##### ❓ What pairs of variables do you think are interesting to look at?

##### ❓ What methods can you use to do this?

##### ❓ Carry out these analyses

💻📊💡 TIP: Things like  `dataframe[["column1", "column2"]].groupby("column1").mean()` are valid Pandas. In SQL this would be `select column1, mean(column2) from dataframe group by column 1`

In [61]:
travel_dataset.groupby("destination")["cost"].mean().sort_values(ascending=False)

destination
Tokyo        2235.295252
Paris        2208.895118
New York     2169.745339
Cairo        2153.272136
Rome         2097.503873
Cape Town    2091.973711
Rio          1960.866707
Sydney       1956.225338
Name: cost, dtype: float64

That rounds up today's session. In the next session we will cover plotting in Python using Matplotlib and Seaborn. Right now all of your data analysis has been tables but plots are a lot more ergonomic to present your results in.